<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="CodePositions.aspx.cs" Inherits="KindergartenWebApp.CodePositions" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindPosition" runat="server" Text="Label">Должность</asp:Label><asp:TextBox ID="TextBoxFindPosition" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindPosition" runat="server" Text="Найти" OnClick="ButtonFindPosition_Click" />
    <br />        
        <asp:GridView ID="GridViewPosition" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewPosition_RowCancelingEdit" 
            OnRowDeleting="GridViewPosition_RowDeleting" 
            OnRowEditing="GridViewPosition_RowEditing" 
            OnRowUpdating="GridViewPosition_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewPosition_PageIndexChanging"
            Caption="Должность" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Код" SortExpression="Id" />
                <asp:BoundField DataField="PositionName" HeaderText="Наименование" SortExpression="PositionName" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новую должность:</strong>
            <br />
            <asp:label runat="server">Наименование:</asp:label><asp:TextBox ID="TextBoxPositionName" runat="server"></asp:TextBox>
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddPosition" runat="server" Text="Добавить" OnClick="ButtonAddPosition_Click" />

        </td>
</tr>
</table>
    </asp:Content>

