<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="CodeGroups.aspx.cs" Inherits="KindergartenWebApp.CodeGroups" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindGroup" runat="server" Text="Label">Группы</asp:Label><asp:TextBox ID="TextBoxFindGroup" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindGroup" runat="server" Text="Найти" OnClick="ButtonFindGroup_Click" />
    <br />        
        <asp:GridView ID="GridViewGroup" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewGroup_RowCancelingEdit" 
            OnRowDeleting="GridViewGroup_RowDeleting" 
            OnRowEditing="GridViewGroup_RowEditing" 
            OnRowUpdating="GridViewGroup_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewGroup_PageIndexChanging"
            Caption="Группа" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Код" SortExpression="Id" />
                <asp:BoundField DataField="GroupName" HeaderText="Наименование группы" SortExpression="GroupName" />
                <asp:TemplateField HeaderText="Сотрудник" SortExpression="StaffId">
                    <EditItemTemplate>
                        <asp:DropDownList ID="StaffDropDownList" runat="server" DataSourceID="SqlDataSourceStaff" DataTextField="FullName" DataValueField="Id" SelectedValue='<%# Bind("StaffId") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                     <asp:Label ID="StaffId" runat="server"  Text='<%# Eval("Staff.FullName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="CountOfChildren" HeaderText="Количество детей" SortExpression="CountOfChildren" />
                <asp:BoundField DataField="YearOfCreation" HeaderText="Год создания" SortExpression="YearOfCreation" />
                <asp:TemplateField HeaderText="Тип группы" SortExpression="GroupType_Id">
                    <EditItemTemplate>
                        <asp:DropDownList ID="TypeDropDownList" runat="server" DataSourceID="SqlDataSourceGroupType" DataTextField="NameOfType" DataValueField="Id" SelectedValue='<%# Bind("GroupType_Id") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                     <asp:Label ID="GroupType_Id" runat="server"  Text='<%# Eval("GroupType.NameOfType") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить группу:</strong>
            <br />
            <asp:label runat="server">наименование группы:</asp:label><asp:TextBox ID="TextBoxNameOfGroup" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Сотрудник:</asp:label><asp:DropDownList ID="StaffDropDownList" DataSourceID="SqlDataSourceStaff" DataValueField="Id" DataTextField="FullName" runat="server"></asp:DropDownList>
            <br />
            <asp:label runat="server">Количество детей:</asp:label><asp:TextBox ID="TextBoxCount" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Год создания:</asp:label><asp:TextBox ID="TextBoxYear" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Тип группы:</asp:label><asp:DropDownList ID="TypeDropDownList" DataSourceID="SqlDataSourceGroupType" DataValueField="Id" DataTextField="NameOfType" runat="server"></asp:DropDownList>
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddGroup" runat="server" Text="Добавить" OnClick="ButtonAddGroup_Click" />

        </td>
</tr>
</table>
    <asp:SqlDataSource ID="SqlDataSourceStaff" runat="server" 
        ConnectionString="<%$ ConnectionStrings:KindergartenConnectionString %>" 
        SelectCommand="SELECT [Id], [FullName] FROM [Staffs]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceGroupType" runat="server" 
        ConnectionString="<%$ ConnectionStrings:KindergartenConnectionString %>" 
        SelectCommand="SELECT [Id], [NameOfType] FROM [GroupTypes]">
    </asp:SqlDataSource>
    </asp:Content>